version: '3.8'

services:
  db:
    image: postgres:15
    container_name: newsapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ii250405
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: newsapi_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Ii250405
      DB_NAME: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
